
ALTER TABLE public.fiscal_data
  ADD COLUMN ecom_jan numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_fev numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_mar numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_avr numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_mai numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_juin numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_juil numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_aout numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_sept numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_oct numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_nov numeric NOT NULL DEFAULT 0,
  ADD COLUMN ecom_dec numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_jan numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_fev numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_mar numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_avr numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_mai numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_juin numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_juil numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_aout numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_sept numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_oct numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_nov numeric NOT NULL DEFAULT 0,
  ADD COLUMN service_dec numeric NOT NULL DEFAULT 0;
