ALTER TABLE public.fiscal_data
  ADD COLUMN IF NOT EXISTS consult_jan numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_fev numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_mar numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_avr numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_mai numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_juin numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_juil numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_aout numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_sept numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_oct numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_nov numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS consult_dec numeric NOT NULL DEFAULT 0;